name: isp-bgp

topology:
  nodes:
    bb1:
      kind: linux
      image: frrouting/frr:v8.1.0
      binds:
        - bb1/daemons:/etc/frr/daemons
        - bb1/frr.conf:/etc/frr/frr.conf
    bb2:
      kind: linux
      image: frrouting/frr:v8.1.0
      binds:
        - bb2/daemons:/etc/frr/daemons
        - bb2/frr.conf:/etc/frr/frr.conf
  links:
    - endpoints: ["bb1:eth5", "bb2:eth5"]

